language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t milhamm/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true milhamm/docker-react npm run test
